<?php


namespace AppBundle\Repository;
/**
 * ActivationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationTokenRepository extends \Doctrine\ORM\EntityRepository
{
}