<?php
/**
 * Created by PhpStorm.
 * User: qwerty
 * Date: 14.01.17
 * Time: 18:36
 */

namespace AppBundle\Repository;


/**
 * PasswordResetTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetTokenRepository extends \Doctrine\ORM\EntityRepository
{
}