# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    access_denied_url: /
    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
            access_denied_handler: app.security.access_denied_handler

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /passwordreset, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: /activation, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /catalog, roles: ROLE_USER }
        - { path: /product, roles: ROLE_MODERATOR }
        - { path: /category, roles: ROLE_MODERATOR }
        - { path: /user, roles: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }