# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

parameters:

services:
    app.security.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]
    app.image_downloader:
        class:        AppBundle\Service\ImageDownloader
        arguments:    ['%images_directory%', '%empty_image%']